version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-buster

    steps:
      - checkout
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline # gets the project dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn package

  publish_image:
    docker:
      - image: docker:20.10.1-git

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Build image
          command: |
            docker build -t "${CIRCLE_PROJECT_REPONAME}" --pull .
      - run:
          name: Publish image
          command: |
            repository="${DOCKER_REGISTRY}/${DOCKER_ORG}/cloudwatch-exporter"
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY

            docker tag "${CIRCLE_PROJECT_REPONAME}" "${repository}:${CIRCLE_SHA1}"
            docker push --quiet "${repository}:${CIRCLE_SHA1}"

            if [[ -n "$CIRCLE_TAG" ]]; then
              docker tag "${CIRCLE_PROJECT_REPONAME}" "${repository}:${CIRCLE_TAG}"
              docker push --quiet "${repository}:${CIRCLE_TAG}"
            fi

            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              docker tag "${CIRCLE_PROJECT_REPONAME}" "${repository}:latest"
              docker push --quiet "${repository}:latest"
            fi
      - run:
          name: Scan image
          command: |
            docker run \
              --env "REPO=quay.io/fundingcircle/$CIRCLE_PROJECT_REPONAME" \
              --env "REGISTRY=https://quay.io" \
              --env DOCKER_USERNAME \
              --env DOCKER_PASSWORD \
              --env "PRISMA_CLOUD_USER=$TWISTCLI_USERNAME" \
              --env "PRISMA_CLOUD_PASSWORD=$TWISTCLI_PASSWORD" \
              --env "TAGS=$CIRCLE_SHA1" \
              --env "GITHUB_TOKEN=$GITHUB_API_TOKEN" \
              --env "GITHUB_REPOSITORY=$CIRCLE_PROJECT_REPONAME" \
              --env "GIT_SHA=$CIRCLE_SHA1" \
              --volume /var/run/docker.sock:/var/run/docker.sock \
              quay.io/fundingcircle/drone-prisma-cloud:1

workflows:
  version: 2
  cloudwatch_exporter:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish_image:
          context: org-global
          requires:
            - build
          filters:
            tags:
              only: /.*/
  nightly:
    jobs:
      - build
      - publish_image:
          context: org-global
          requires:
            - build
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only: master
