version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-buster

    steps:
      - checkout
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline # gets the project dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn package

  publish_image:
    docker:
      - image: circleci/openjdk:11-jdk-buster

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: |
          repository="${DOCKER_REGISTRY}/${DOCKER_ORG}/cloudwatch-exporter"
          docker build -t ${repository}:latest --pull .
          if [[ -n "$CIRCLE_TAG" ]]; then
            docker tag -t ${repository}:"${CIRCLE_TAG}" ${repository}:latest
          fi
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
      - run: |
          docker push ${repository}:latest
          if [[ -n "$CIRCLE_TAG" ]]; then
            docker push ${repository}:"${CIRCLE_TAG}"
          fi

workflows:
  version: 2
  cloudwatch_exporter:
    jobs:
      - build
      - publish_image:
          context: org-global
          requires:
            - build
